services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=parsaghasemi
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=tmootybackenddb
    ports:
      - 3000:5432
